### ISSUE TITLE
Cannot invoke "org.purpurmc.purpur.gui.GUIColor.getColor()" because "guiColor" is null

### ISSUE THREAD

**Issue by NeglectDream** [HaHaWTH/AdvancedSensitiveWords#47]
[23:08:23] [Server thread/INFO]: [AdvancedSensitiveWords] Loading server plugin AdvancedSensitiveWords v1.0
[23:08:23] [AWT-EventQueue-0/WARN]: Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "org.purpurmc.purpur.gui.GUIColor.getColor()" because "guiColor" is null
[23:08:23] [AWT-EventQueue-0/WARN]: 	at org.purpurmc.purpur.gui.JColorTextPane.append(JColorTextPane.java:37)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at net.minecraft.server.gui.MinecraftServerGui.print(MinecraftServerGui.java:272)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at net.minecraft.server.gui.MinecraftServerGui.lambda$print$2(MinecraftServerGui.java:254)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[23:08:23] [AWT-EventQueue-0/WARN]: 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by HaHaWTH** [comment]
Are you sure its caused by ASW?
